apiVersion: v1
kind: Namespace
metadata:
  name: els
---
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: els
spec:
  version: 7.5.1
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
  - name: default
    count: 1
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: analysis-ik
          securityContext:
            privileged: true
          command: ['./bin/elasticsearch-plugin', 'install', 'https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.5.1/elasticsearch-analysis-ik-7.5.1.zip']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 4Gi
              cpu: 2
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: default
                topologyKey: kubernetes.io/hostname
          # nodeAffinity:
          #   requiredDuringSchedulingIgnoredDuringExecution: 
          #     nodeSelectorTerms:
          #     - matchExpressions:
          #       - key: kubernetes.io/hostname
          #         operator: In
          #         values:
          #           - es-1
          #           - es-2
          #           - es-3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1000Gi
  config:
      node.master: true
      node.data: true
      node.ingest: true
      home.path: '/elastic'
      xpack.security:
        authc:
          realms:
            native:
              native1:
                order: 1