---
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: sekibana
  namespace: els
spec:
  version: 7.5.1
  count: 1
  elasticsearchRef:
    name: seelasticsearch
  http:
    service:
      spec:
        type: LoadBalancer
    # tls:
    #   selfSignedCertificate:
    #     disabled: true