apiVersion: v1
kind: Pod
metadata:
  name: crawler
  namespace: els
spec:
  containers:
  - name: crawler
    image: t106362512/crawler
    imagePullPolicy: Always
    env:
    - name: LOGGING_LEVEL
      value: "INFO"
    - name: ROOT_INDEX
      value: "ptt"
    - name: ELASTICSEARCH_ENDPOINT
      # value: "20.43.169.93:9200"
      value: "elastic-es-http.els:9200"
    - name: ELASTICSEARCH_USER
      # value: "t106362501"
      value: "elastic"
    - name: ELASTICSEARCH_PASSWD
      valueFrom:
          secretKeyRef:
            name: elastic-es-elastic-user
            key: elastic
  restartPolicy: OnFailure